SSHAGENT=/usr/bin/ssh-agent
SSHADD=/usr/bin/ssh-add
SSHAGENTARGS="-s"
if [ -z "$SSH_AUTH_SOCK" -a -x "$SSHAGENT" ]; then
  eval `$SSHAGENT $SSHAGENTARGS`
  trap "kill $SSH_AGENT_PID" 0
fi
eval `$SSHADD`
